/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pt_fraunhofer_pulse_Pulse_Face */

#ifndef _Included_pt_fraunhofer_pulse_Pulse_Face
#define _Included_pt_fraunhofer_pulse_Pulse_Face
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pt_fraunhofer_pulse_Pulse_Face
 * Method:    _id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_pt_fraunhofer_pulse_Pulse_00024Face__1id
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pt_fraunhofer_pulse_Pulse_Face
 * Method:    _box
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_pt_fraunhofer_pulse_Pulse_00024Face__1box
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     pt_fraunhofer_pulse_Pulse_Face
 * Method:    _bpm
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_pt_fraunhofer_pulse_Pulse_00024Face__1bpm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pt_fraunhofer_pulse_Pulse_Face
 * Method:    _pulse
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_pt_fraunhofer_pulse_Pulse_00024Face__1pulse
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     pt_fraunhofer_pulse_Pulse_Face
 * Method:    _existsPulse
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_pt_fraunhofer_pulse_Pulse_00024Face__1existsPulse
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
